### ISSUE TITLE
Add wiki documentation for the templates system

### ISSUE THREAD

**Issue by andstor** [KQMATH/moodle-qtype_shortmath#59]
# Overview
The templates system needs to be properly documented.

## Tasks
- [ ] Create wiki page for template system overview
- [ ] Create wiki page for template management
- [ ] Create wiki page for template creation/editing
